<%
def box_for_provider(distro)
  case ENV.fetch('VAGRANT_DEFAULT_PROVIDER', 'virtualbox')
    when 'virtualbox' then "bento/#{distro}"
    when 'docker' then "tknerr/baseimage-#{distro}"
    else raise 'unsupported provider!'
  end
end
%>
---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.4.1
  chef_omnibus_install_options: -d /tmp/vagrant-cache/vagrant_omnibus
  client_rb: 
    add_formatter: min

platforms:
- name: ubuntu-12.04
  driver_config:
    box: <%= box_for_provider('ubuntu-12.04') %>
    network:
      - ["forwarded_port", {guest: 80, host: 8080}]
    customize:
      memory: 128
- name: ubuntu-14.04
  driver_config:
    box: <%= box_for_provider('ubuntu-14.04') %>
    network:
      - ["forwarded_port", {guest: 80, host: 9080}]
    customize:
      memory: 128

suites:
- name: default
  run_list: ["recipe[sample-app]"]
  attributes:
    sample_app:
      words_of_wisdom: 'test all the things!'
