---
driver:
  name: vagrant

platforms:
- name: ubuntu-12.04
  driver_config:
    box: fgrehm/precise64-lxc
    customize:
      cgroup.memory.limit_in_bytes: 128M
- name: ubuntu-14.04
  driver_config:
    box: fgrehm/trusty64-lxc
    customize:
      cgroup.memory.limit_in_bytes: 128M
