---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.0.3
  chef_omnibus_install_options: -d /tmp/vagrant-cache/vagrant_omnibus

platforms:
- name: ubuntu-12.04
  driver_config:
    box: ubuntu/precise32
    box_url: https://atlas.hashicorp.com/ubuntu/boxes/precise32/versions/12.04.4/providers/virtualbox.box
    customize:
      memory: 128
- name: ubuntu-14.04
  driver_config:
    box: ubuntu/trusty64
    box_url: https://atlas.hashicorp.com/ubuntu/boxes/trusty64/versions/14.04/providers/virtualbox.box
    customize:
      memory: 256

suites:
- name: default
  run_list: ["recipe[sample-app]"]
  attributes: {}
